//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinearErrorCorrectingCoders {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinearErrorCorrectingCoders.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string AttentionExclamation {
            get {
                return ResourceManager.GetString("AttentionExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code length({0}) is not complies to length of coder ({1}).
        /// </summary>
        internal static string BadCodeLen {
            get {
                return ResourceManager.GetString("BadCodeLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code:.
        /// </summary>
        internal static string Code_ {
            get {
                return ResourceManager.GetString("Code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code field is empty!.
        /// </summary>
        internal static string CodeFieldIsEmptyExclamation {
            get {
                return ResourceManager.GetString("CodeFieldIsEmptyExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Code length:.
        /// </summary>
        internal static string CodeLength_ {
            get {
                return ResourceManager.GetString("CodeLength_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Coder is not set!.
        /// </summary>
        internal static string CoderNotSetExclamation {
            get {
                return ResourceManager.GetString("CoderNotSetExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data:.
        /// </summary>
        internal static string Data_ {
            get {
                return ResourceManager.GetString("Data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data length:.
        /// </summary>
        internal static string DataLength_ {
            get {
                return ResourceManager.GetString("DataLength_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string ErrorExclamation {
            get {
                return ResourceManager.GetString("ErrorExclamation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hamming.
        /// </summary>
        internal static string Hamming {
            get {
                return ResourceManager.GetString("Hamming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hamming ext..
        /// </summary>
        internal static string HammingExt {
            get {
                return ResourceManager.GetString("HammingExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Inverse.
        /// </summary>
        internal static string Inverse {
            get {
                return ResourceManager.GetString("Inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pairity of all.
        /// </summary>
        internal static string PairityOfAll {
            get {
                return ResourceManager.GetString("PairityOfAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat count:.
        /// </summary>
        internal static string RepeatCount_ {
            get {
                return ResourceManager.GetString("RepeatCount_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syndrome:.
        /// </summary>
        internal static string Syndrome_ {
            get {
                return ResourceManager.GetString("Syndrome_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Syndrome length:.
        /// </summary>
        internal static string SyndromeLength_ {
            get {
                return ResourceManager.GetString("SyndromeLength_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update code.
        /// </summary>
        internal static string UpdateCode {
            get {
                return ResourceManager.GetString("UpdateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update syndrome.
        /// </summary>
        internal static string UpdateSyndrome {
            get {
                return ResourceManager.GetString("UpdateSyndrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You must fill Data field!.
        /// </summary>
        internal static string YouMustFillDataExclamation {
            get {
                return ResourceManager.GetString("YouMustFillDataExclamation", resourceCulture);
            }
        }
    }
}
